// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF7th9kYkGf8xOpCSXmwEXz-CMXmlnHCg',
    appId: '1:666819274100:web:ae6c89e0cd81cdbff57821',
    messagingSenderId: '666819274100',
    projectId: 'commiploy',
    authDomain: 'commiploy.firebaseapp.com',
    databaseURL: 'https://commiploy-default-rtdb.firebaseio.com',
    storageBucket: 'commiploy.appspot.com',
    measurementId: 'G-5DHCYBKSP8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6Unq1okMji5nu8rO4DrIKIe9sZgW5cnQ',
    appId: '1:666819274100:android:c14b7aaf358ac3c1f57821',
    messagingSenderId: '666819274100',
    projectId: 'commiploy',
    databaseURL: 'https://commiploy-default-rtdb.firebaseio.com',
    storageBucket: 'commiploy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1hmZr58EdEG_tNh89fMdleIwqF9q2eNM',
    appId: '1:666819274100:ios:c3ddf41c9c29be6ff57821',
    messagingSenderId: '666819274100',
    projectId: 'commiploy',
    databaseURL: 'https://commiploy-default-rtdb.firebaseio.com',
    storageBucket: 'commiploy.appspot.com',
    iosClientId: '666819274100-l8v8ljqjqifnvogea3mo1kudg6m8rm47.apps.googleusercontent.com',
    iosBundleId: 'com.softglitchsolutions.commiploy',
  );
}
