// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT8BloF5FpXv60_9y0Mf9oj7EqCAA_D_I',
    appId: '1:909031550117:web:d898f42cdcf68b79a1314c',
    messagingSenderId: '909031550117',
    projectId: 'commiploy-354323',
    authDomain: 'commiploy-354323.firebaseapp.com',
    databaseURL: 'https://commiploy-354323-default-rtdb.firebaseio.com',
    storageBucket: 'commiploy-354323.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChhdryEfnJ3GoiymPghFZh93T7w5-lxKU',
    appId: '1:909031550117:android:b1d88faa61f146caa1314c',
    messagingSenderId: '909031550117',
    projectId: 'commiploy-354323',
    databaseURL: 'https://commiploy-354323-default-rtdb.firebaseio.com',
    storageBucket: 'commiploy-354323.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMy-A5-19aEZixPx5i3FEtKFsC1YUoLXs',
    appId: '1:909031550117:ios:08263f7e9a79e902a1314c',
    messagingSenderId: '909031550117',
    projectId: 'commiploy-354323',
    databaseURL: 'https://commiploy-354323-default-rtdb.firebaseio.com',
    storageBucket: 'commiploy-354323.appspot.com',
    iosClientId: '909031550117-lt8mejeilf06n6kmhhk26rviqcbtn3oj.apps.googleusercontent.com',
    iosBundleId: 'com.softglitchsolutions.commiploy',
  );
}
